name: ci

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install pre-commit~=2.2
          # TODO! change `pre-commit~=2.2` to `.[devtools]`
          # ! once aiida-aurora dependency issue is resolved

      - name: Run pre-commit hooks
        run: |
          pre-commit install
          pre-commit run --all-files
